/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editorTextos;

import java.awt.FileDialog;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.undo.UndoManager;
import javax.swing.undo.CannotRedoException;

/**
 *
 * @author Diana
 */
public class Bloc extends javax.swing.JFrame implements ActionListener {

  
    String nombreArchivo;
    UndoManager undo;
    int checar=0;
    Find buscar;
    /**
     * Creates new form Bloc
     */
    public Bloc() {
        
        initComponents();
        JFileChooser File = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Text Files", "txt");
     File.addChoosableFileFilter( filtro );
  undo = new UndoManager();
jTextArea.getDocument().addUndoableEditListener(
                new UndoableEditListener() {
                    public void undoableEditHappened(UndoableEditEvent e) {
                        undo.addEdit(e.getEdit());
                }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButtonNew = new javax.swing.JButton();
        jButtonAbrir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCopiar = new javax.swing.JButton();
        jButtonCortar = new javax.swing.JButton();
        jButtonPegar = new javax.swing.JButton();
        jButtonDeshacer = new javax.swing.JButton();
        jButtonRehacer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoM = new javax.swing.JMenu();
        nuevoFile = new javax.swing.JMenuItem();
        abrirFile = new javax.swing.JMenuItem();
        guardarFile = new javax.swing.JMenuItem();
        salirFile = new javax.swing.JMenuItem();
        editarM = new javax.swing.JMenu();
        deshacer = new javax.swing.JMenuItem();
        rehacer = new javax.swing.JMenuItem();
        cortar = new javax.swing.JMenuItem();
        copiar = new javax.swing.JMenuItem();
        pegar = new javax.swing.JMenuItem();
        selectAll = new javax.swing.JMenuItem();
        buscarM = new javax.swing.JMenu();
        find = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("jMenu9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bloc");
        setBackground(new java.awt.Color(0, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage(Bloc.class.getResource("/img/editor-de-texto.png")));

        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jButtonNew.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/window-new.png"))); // NOI18N
        jButtonNew.setToolTipText("");
        jButtonNew.addActionListener(this);

        jButtonAbrir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cd_catalogue_1.png"))); // NOI18N
        jButtonAbrir.addActionListener(this);

        jButtonGuardar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b_save.png"))); // NOI18N
        jButtonGuardar.addActionListener(this);

        jButtonCopiar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy_edit.png"))); // NOI18N
        jButtonCopiar.addActionListener(this);

        jButtonCortar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cut_edit.png"))); // NOI18N
        jButtonCortar.addActionListener(this);

        jButtonPegar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paste_edit.png"))); // NOI18N
        jButtonPegar.addActionListener(this);

        jButtonDeshacer.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/undo_edit.png"))); // NOI18N
        jButtonDeshacer.addActionListener(this);

        jButtonRehacer.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRehacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/redo_edit.png"))); // NOI18N
        jButtonRehacer.addActionListener(this);

        archivoM.setText("Archivo");
        archivoM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        nuevoFile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nuevoFile.setText("Nuevo");
        nuevoFile.addActionListener(this);
        archivoM.add(nuevoFile);

        abrirFile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        abrirFile.setText("Abrir");
        abrirFile.addActionListener(this);
        archivoM.add(abrirFile);

        guardarFile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        guardarFile.setText("Guardar");
        guardarFile.addActionListener(this);
        archivoM.add(guardarFile);

        salirFile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        salirFile.setText("Salir");
        salirFile.addActionListener(this);
        archivoM.add(salirFile);

        jMenuBar1.add(archivoM);

        editarM.setText("Editar");
        editarM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        deshacer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deshacer.setText("Deshacer");
        deshacer.addActionListener(this);
        editarM.add(deshacer);

        rehacer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rehacer.setText("Rehacer");
        rehacer.addActionListener(this);
        editarM.add(rehacer);

        cortar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cortar.setText("Cortar");
        cortar.addActionListener(this);
        editarM.add(cortar);

        copiar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        copiar.setText("Copiar");
        copiar.addActionListener(this);
        editarM.add(copiar);

        pegar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pegar.setText("Pegar");
        pegar.addActionListener(this);
        editarM.add(pegar);

        selectAll.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        selectAll.setText("Select all");
        selectAll.addActionListener(this);
        editarM.add(selectAll);

        jMenuBar1.add(editarM);

        buscarM.setText("Buscar");
        buscarM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        find.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        find.setText("Find");
        find.addActionListener(this);
        buscarM.add(find);

        jMenuBar1.add(buscarM);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jButtonNew)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonAbrir)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonGuardar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonCopiar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonCortar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonPegar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonDeshacer)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonRehacer)
                        .add(0, 318, Short.MAX_VALUE))
                    .add(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jButtonNew, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButtonAbrir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .add(jButtonGuardar)
                    .add(jButtonCopiar)
                    .add(jButtonCortar)
                    .add(jButtonPegar)
                    .add(jButtonDeshacer)
                    .add(jButtonRehacer))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButtonNew) {
            Bloc.this.jButtonNewActionPerformed(evt);
        }
        else if (evt.getSource() == jButtonAbrir) {
            Bloc.this.jButtonAbrirActionPerformed(evt);
        }
        else if (evt.getSource() == jButtonGuardar) {
            Bloc.this.jButtonGuardarActionPerformed(evt);
        }
        else if (evt.getSource() == jButtonCopiar) {
            Bloc.this.jButtonCopiarActionPerformed(evt);
        }
        else if (evt.getSource() == jButtonCortar) {
            Bloc.this.jButtonCortarActionPerformed(evt);
        }
        else if (evt.getSource() == jButtonPegar) {
            Bloc.this.jButtonPegarActionPerformed(evt);
        }
        else if (evt.getSource() == jButtonDeshacer) {
            Bloc.this.jButtonDeshacerActionPerformed(evt);
        }
        else if (evt.getSource() == jButtonRehacer) {
            Bloc.this.jButtonRehacerActionPerformed(evt);
        }
        else if (evt.getSource() == nuevoFile) {
            Bloc.this.nuevoFileActionPerformed(evt);
        }
        else if (evt.getSource() == abrirFile) {
            Bloc.this.abrirFileActionPerformed(evt);
        }
        else if (evt.getSource() == guardarFile) {
            Bloc.this.guardarFileActionPerformed(evt);
        }
        else if (evt.getSource() == salirFile) {
            Bloc.this.salirFileActionPerformed(evt);
        }
        else if (evt.getSource() == deshacer) {
            Bloc.this.deshacerActionPerformed(evt);
        }
        else if (evt.getSource() == rehacer) {
            Bloc.this.rehacerActionPerformed(evt);
        }
        else if (evt.getSource() == cortar) {
            Bloc.this.cortarActionPerformed(evt);
        }
        else if (evt.getSource() == copiar) {
            Bloc.this.copiarActionPerformed(evt);
        }
        else if (evt.getSource() == pegar) {
            Bloc.this.pegarActionPerformed(evt);
        }
        else if (evt.getSource() == selectAll) {
            Bloc.this.selectAllActionPerformed(evt);
        }
        else if (evt.getSource() == find) {
            Bloc.this.findActionPerformed(evt);
        }
    }//GEN-END:initComponents

    private void nuevoFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoFileActionPerformed
        // TODO add your handling code here:
    Nuevo();
    }//GEN-LAST:event_nuevoFileActionPerformed
private void Nuevo(){
        jTextArea.setText("");
        setTitle(nombreArchivo);
}
    private void abrirFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirFileActionPerformed
        abrir();
    }//GEN-LAST:event_abrirFileActionPerformed

    public void abrir(){
                FileDialog fileDialog=new FileDialog(Bloc.this, "Abrir archivo", FileDialog.LOAD);
        fileDialog.setVisible(true);
        if(fileDialog.getFile()!=null){
            nombreArchivo=fileDialog.getDirectory() + fileDialog.getFile();
            setTitle(nombreArchivo);
        }
        try {
            BufferedReader leer=new BufferedReader(new FileReader(nombreArchivo));
            StringBuilder sb=new StringBuilder();
            String linea=null;
            
            while ((linea=leer.readLine()) != null) {
                sb.append(linea + "\n");
                jTextArea.setText(sb.toString());
            }
            leer.close();
        } catch (IOException e) {
            System.out.println("Archivo no encontrado");
            
        }
        
        
    }
    private void guardar(){
        FileDialog fileDialog=new FileDialog(Bloc.this, "Guardar archivo", FileDialog.SAVE);
         fileDialog.setVisible(true);
         if (fileDialog.getFile() != null) {
            nombreArchivo=fileDialog.getDirectory() + fileDialog.getFile();
             setTitle(nombreArchivo);
        }
         try {
             FileWriter fileWriter=new FileWriter(nombreArchivo);
             fileWriter.write(jTextArea.getText());
             setTitle(nombreArchivo);
             fileWriter.close();
        } catch (IOException e) {
             System.out.println("Archivo no encontrado");
        }
    }
    private void guardarFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarFileActionPerformed
        // TODO add your handling code here:
        guardar();
        
    }//GEN-LAST:event_guardarFileActionPerformed

    private void salirFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirFileActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirFileActionPerformed

    private void rehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rehacerActionPerformed
        // TODO add your handling code here:
        try {
            undo.redo();
        } catch (CannotRedoException c) {
            c.printStackTrace();
        }
    }//GEN-LAST:event_rehacerActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
         Nuevo();
       
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarActionPerformed
        // TODO add your handling code here:
    copiar();
    }//GEN-LAST:event_copiarActionPerformed
private void copiar(){
        jTextArea.copy();
}
    private void pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegarActionPerformed
        // TODO add your handling code here:
        pegar();
    
    }//GEN-LAST:event_pegarActionPerformed
private void pegar(){
        jTextArea.paste();
}
    private void cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortarActionPerformed
        // TODO add your handling code here:
         cortar();
    }//GEN-LAST:event_cortarActionPerformed
private void cortar(){
    jTextArea.cut();
}
    private void deshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deshacerActionPerformed
        // TODO add your handling code here:
        deshacer();
    
    }//GEN-LAST:event_deshacerActionPerformed
private void deshacer(){
          try {
            undo.undo();
        } catch (CannotRedoException c) {
            c.printStackTrace();
        }
}
    private void selectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllActionPerformed
        // TODO add your handling code here:
         jTextArea.selectAll();
    }//GEN-LAST:event_selectAllActionPerformed

    private void jButtonCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopiarActionPerformed
        // TODO add your handling code here:
        copiar();
    }//GEN-LAST:event_jButtonCopiarActionPerformed

    private void jButtonCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCortarActionPerformed
cortar();
    }//GEN-LAST:event_jButtonCortarActionPerformed

    private void jButtonPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPegarActionPerformed
pegar();
    }//GEN-LAST:event_jButtonPegarActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        
        Find f=new Find();
        f.setVisible(true);
    }//GEN-LAST:event_findActionPerformed
private void rehacer(){
    try {
            undo.redo();
        } catch (CannotRedoException c) {
            c.printStackTrace();
        }
}
    
    private void jButtonDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeshacerActionPerformed
        deshacer();
    }//GEN-LAST:event_jButtonDeshacerActionPerformed

    private void jButtonRehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRehacerActionPerformed
rehacer();
    }//GEN-LAST:event_jButtonRehacerActionPerformed

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        // TODO add your handling code here:
        abrir();
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bloc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenuItem abrirFile;
    javax.swing.JMenu archivoM;
    javax.swing.JMenu buscarM;
    javax.swing.JMenuItem copiar;
    javax.swing.JMenuItem cortar;
    javax.swing.JMenuItem deshacer;
    javax.swing.JMenu editarM;
    javax.swing.JMenuItem find;
    javax.swing.JMenuItem guardarFile;
    javax.swing.JButton jButtonAbrir;
    javax.swing.JButton jButtonCopiar;
    javax.swing.JButton jButtonCortar;
    javax.swing.JButton jButtonDeshacer;
    javax.swing.JButton jButtonGuardar;
    javax.swing.JButton jButtonNew;
    javax.swing.JButton jButtonPegar;
    javax.swing.JButton jButtonRehacer;
    javax.swing.JMenu jMenu3;
    javax.swing.JMenu jMenu4;
    javax.swing.JMenu jMenu5;
    javax.swing.JMenu jMenu6;
    javax.swing.JMenu jMenu7;
    javax.swing.JMenu jMenu8;
    javax.swing.JMenu jMenu9;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JMenuBar jMenuBar2;
    javax.swing.JMenuBar jMenuBar3;
    javax.swing.JMenuBar jMenuBar4;
    javax.swing.JPopupMenu jPopupMenu1;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextArea jTextArea;
    javax.swing.JMenuItem nuevoFile;
    javax.swing.JMenuItem pegar;
    javax.swing.JMenuItem rehacer;
    javax.swing.JMenuItem salirFile;
    javax.swing.JMenuItem selectAll;
    // End of variables declaration//GEN-END:variables
}
