/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import controller.AccesoController;
import gestorFondoPantalla.Escritorio;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.SystemColor;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Usuario;

/**
 *
 * @author Diana
 */
public class Login1 extends javax.swing.JFrame implements ActionListener, KeyListener {
private final Dimension dim;
    /**
     * Creates new form Login1
     */
    public Login1() {
        initComponents();
  		 dim=super.getToolkit().getScreenSize();
	        super.setSize(dim);
	        super.setUndecorated(true);
	        super.setVisible(true);
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        TextFieldUsuario = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        errorPassword = new javax.swing.JLabel();
        errorUsuario = new javax.swing.JLabel();
        btnApagar = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoFinal2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 76, 343, 347));

        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/man-3.png"))); // NOI18N
        jLabelUsuario.setAlignmentX(0.5F);
        jLabelUsuario.setName(""); // NOI18N
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 212, 161));

        jLabelPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/002-unlock.png"))); // NOI18N
        jPanel1.add(jLabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 115, -1));

        TextFieldUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextFieldUsuario.addActionListener(this);
        TextFieldUsuario.addKeyListener(this);
        jPanel1.add(TextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 270, 40));

        passwordfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordfield.addKeyListener(this);
        jPanel1.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 270, 40));

        btnAceptar.setBackground(new java.awt.Color(204, 204, 204));
        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(new javax.swing.border.MatteBorder(null));
        btnAceptar.addActionListener(this);
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 590, 160, 60));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.MatteBorder(null));
        btnCancelar.addActionListener(this);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 170, 60));

        errorPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error.png"))); // NOI18N
        errorPassword.setVisible(false);
        jPanel1.add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 390, -1, 70));

        errorUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error.png"))); // NOI18N
        errorUsuario.setVisible(false);
        jPanel1.add(errorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, 70));

        btnApagar.setBackground(new java.awt.Color(0, 0, 0));
        btnApagar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnApagar.setForeground(new java.awt.Color(255, 255, 255));
        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/radio_button_selected (1).png"))); // NOI18N
        btnApagar.setText("Apagar");
        btnApagar.setBorder(null);
        btnApagar.setBorderPainted(false);
        btnApagar.addActionListener(this);
        jPanel1.add(btnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 670, 180, -1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 769, 541);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == TextFieldUsuario) {
            Login1.this.TextFieldUsuarioActionPerformed(evt);
        }
        else if (evt.getSource() == btnAceptar) {
            Login1.this.btnAceptarActionPerformed(evt);
        }
        else if (evt.getSource() == btnCancelar) {
            Login1.this.btnCancelarActionPerformed(evt);
        }
        else if (evt.getSource() == btnApagar) {
            Login1.this.btnApagarActionPerformed(evt);
        }
    }

    public void keyPressed(java.awt.event.KeyEvent evt) {
    }

    public void keyReleased(java.awt.event.KeyEvent evt) {
    }

    public void keyTyped(java.awt.event.KeyEvent evt) {
        if (evt.getSource() == TextFieldUsuario) {
            Login1.this.TextFieldUsuarioKeyTyped(evt);
        }
        else if (evt.getSource() == passwordfield) {
            Login1.this.passwordfieldKeyTyped(evt);
        }
    }//GEN-END:initComponents

    private void TextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldUsuarioActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        AccesoController accesoController = new AccesoController();
        Usuario autenticado = accesoController.autenticarUsuario(TextFieldUsuario.getText(),
                                String.valueOf(passwordfield.getPassword()));
        if (autenticado != null) {
            JOptionPane.showMessageDialog(null, "Bienvenido: " + autenticado.getUsername());
            dispose();
            Escritorio e=new Escritorio();
            e.setVisible(true);
        } else if(TextFieldUsuario.getText().equals("")) {
             errorUsuario.setVisible(true);
                            TextFieldUsuario.setCaretColor(Color.RED);
                            TextFieldUsuario.requestFocus();
        }else if(passwordfield.getText().equals("")){
            errorPassword.setVisible(true);
                           passwordfield.setCaretColor(Color.RED);
                            passwordfield.requestFocus();
        }else{
              JOptionPane.showMessageDialog(null, "Usuario y/o Contrasenia incorrecta","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
//dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void TextFieldUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldUsuarioKeyTyped
         errorUsuario.setVisible(false);
         TextFieldUsuario.setCaretColor(Color.black);
    }//GEN-LAST:event_TextFieldUsuarioKeyTyped

    private void passwordfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordfieldKeyTyped
        errorPassword.setVisible(false);
         passwordfield.setCaretColor(Color.black);
    }//GEN-LAST:event_passwordfieldKeyTyped

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true); 
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField TextFieldUsuario;
    javax.swing.JButton btnAceptar;
    javax.swing.JButton btnApagar;
    javax.swing.JButton btnCancelar;
    javax.swing.JLabel errorPassword;
    javax.swing.JLabel errorUsuario;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabelPass;
    javax.swing.JLabel jLabelUsuario;
    javax.swing.JMenuItem jMenuItem1;
    javax.swing.JPanel jPanel1;
    javax.swing.JPasswordField passwordfield;
    // End of variables declaration//GEN-END:variables
}
